version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    command: gunicorn djangoproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/srv/flights/staticfiles
      - media_volume:/srv/flights/mediafiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11.4
    volumes:
      - postgres_data:/srv/flights/postgres
    env_file: .env.db
  nginx:
    build: ./deploy/nginx
    volumes:
      - static_volume:/srv/flights/staticfiles
      - media_volume:/srv/flights/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: