"""
"initial"

Revision ID: f3e8691bba9c
Revises: 
Create Date: 2019-07-14 23:48:17.519237
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('iata', sa.String(), nullable=True),
                    sa.Column('icao', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('airport',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('tz_offset', sa.Numeric(), nullable=True),
                    sa.Column('tz', sa.String(), nullable=True),
                    sa.Column('iata', sa.String(), nullable=True),
                    sa.Column('icao', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('fares_search_request',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('partner_request_id', sa.String(), nullable=False),
                    sa.Column('partner_tag', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('fares_trip',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('fares_flight',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order', sa.SmallInteger(), nullable=False),
                    sa.Column('trip_id', sa.Integer(), nullable=False),
                    sa.Column('carrier_id', sa.Integer(), nullable=True),
                    sa.Column('flight_number', sa.String(), nullable=True),
                    sa.Column('source_id', sa.Integer(), nullable=False),
                    sa.Column('destination_id', sa.Integer(), nullable=False),
                    sa.Column('departure', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('arrival', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('service_class', sa.String(), nullable=True),
                    sa.Column('ticket_type', sa.String(), nullable=True),
                    sa.Column('number_of_stops', sa.Integer(), nullable=True),
                    sa.Column('fare_basis', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['carrier_id'], ['airline.id'], ),
                    sa.ForeignKeyConstraint(['destination_id'], ['airport.id'], ),
                    sa.ForeignKeyConstraint(['source_id'], ['airport.id'], ),
                    sa.ForeignKeyConstraint(['trip_id'], ['fares_trip.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_fares_flight_carrier_id'), 'fares_flight', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_fares_flight_destination_id'), 'fares_flight', ['destination_id'], unique=False)
    op.create_index(op.f('ix_fares_flight_source_id'), 'fares_flight', ['source_id'], unique=False)
    op.create_index(op.f('ix_fares_flight_trip_id'), 'fares_flight', ['trip_id'], unique=False)
    op.create_table('fares_itinerary',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('request_id', sa.Integer(), nullable=False),
                    sa.Column('onward_trip_id', sa.Integer(), nullable=False),
                    sa.Column('return_trip_id', sa.Integer(), nullable=True),
                    sa.Column('price_adult', sa.Numeric(), nullable=True),
                    sa.Column('price_child', sa.Numeric(), nullable=True),
                    sa.Column('price_infant', sa.Numeric(), nullable=True),
                    sa.Column('price_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(['onward_trip_id'], ['fares_trip.id'], ),
                    sa.ForeignKeyConstraint(['request_id'], ['fares_search_request.id'], ),
                    sa.ForeignKeyConstraint(['return_trip_id'], ['fares_trip.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_fares_itinerary_onward_trip_id'), 'fares_itinerary', ['onward_trip_id'], unique=False)
    op.create_index(op.f('ix_fares_itinerary_return_trip_id'), 'fares_itinerary', ['return_trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fares_itinerary_return_trip_id'), table_name='fares_itinerary')
    op.drop_index(op.f('ix_fares_itinerary_onward_trip_id'), table_name='fares_itinerary')
    op.drop_table('fares_itinerary')
    op.drop_index(op.f('ix_fares_flight_trip_id'), table_name='fares_flight')
    op.drop_index(op.f('ix_fares_flight_source_id'), table_name='fares_flight')
    op.drop_index(op.f('ix_fares_flight_destination_id'), table_name='fares_flight')
    op.drop_index(op.f('ix_fares_flight_carrier_id'), table_name='fares_flight')
    op.drop_table('fares_flight')
    op.drop_table('fares_trip')
    op.drop_table('fares_search_request')
    op.drop_table('airport')
    op.drop_table('airline')
    # ### end Alembic commands ###
